#!/bin/bash

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <path to app source>"
  exit 1
fi


source=$1
args=${2:-""}
tmpdir=$(mktemp -d)

echo "Scanning ${source}"
for scanner in tools.d/*; do
  name=$(basename "${scanner}")
  report="${tmpdir}/${name}.sarif"
  echo "Running ${name} and reporting to ${report}"
  bash "$scanner" "$source" > "${report}" || rm -f "${report}"
done
echo "Scanning complete.  Reports found:"
ls ${tmpdir}

if [ -z "${args}" ]; then
  echo "Summary:"
  sarif summary "${tmpdir}"/*.sarif
elif [ "$args" == "html" ]; then
  echo "HTML report at:"

  html_report="${source}/statica.html"
  export REPO_URL=$(cd ${source} && git config --get remote.origin.url)
  export REPO_BRANCH=$(cd ${source} && git rev-parse --abbrev-ref HEAD)
  export LATEST_COMMIT_SHA=$(cd ${source} && git rev-parse --short HEAD )

  ./html_report.rb "${tmpdir}" "${html_report}"
  echo "${html_report}"
fi

rm -rf "${tmpdir}"
