#!/bin/bash

set -euo pipefail
which -s checkov || exit 1

source=$1

out=$(mktemp -d)
checkov --quiet -d "${source}" -o sarif --output-file-path "${out}" 1>&2
cat "${out}/results_sarif.sarif"
rm -rf "${out}"