#!/bin/bash

which git > /dev/null || exit 1

source=$1
tmpdir=$(mktemp -d)
OUTPUT="${tmpdir}/churned"
CSV="${tmpdir}/findings.csv"
TOP_N_CHURNED_FILES=10

git -C "${source}" log --format=format: --name-only --since=12.month \
 | grep -Ev '^$' \
 | sort \
 | uniq -c \
 | sort -nr \
 | head -${TOP_N_CHURNED_FILES} \
 | awk '{print $2, $1}' > "${OUTPUT}"

while read -r filename _commits; do
  printf "%s,%s,%s,%s,%s,%s\n" "top-file-churns" "note" "File has been committed to frequently. This may indicate design issues." "${filename}" 0 0 >> "$CSV"
done < "${OUTPUT}"
./2sarif.rb "churn" "$(git --version)" "$CSV"

# clean up
rm -rf "${tmpdir}"
