#!/bin/bash

set -euo pipefail
which -s dependency-check || exit 1

source=$1

out=$(mktemp -d)
dependency-check -s "${source}" -o ${out}/report.sarif --format SARIF  --enableRetired  --nvdValidForHours 1000 > "${out}/log"
cat "${out}"/report.sarif
rm -rf "${out}"
