#!/bin/bash

set -euo pipefail
which -s jscpd || exit 1
npm ls -g | grep -q jscpd-sarif-reporter || exit 1

MIN_LINES=15
MIN_TOKENS=150
SCAN_MODE=strict
# runtime params
source=$1
tmpdir=$(mktemp -d)

# run command and send output to stderr, sarif to file, send sarif to stdout
jscpd -l "${MIN_LINES}" -k "${MIN_TOKENS}" -m ${SCAN_MODE} -i "*/packages/*" --reporters sarif -o "${tmpdir}" "${source}" 1>&2
sed -E 's/(Clone detected in [a-z0-9]+),[^"]+/\1/g' "${tmpdir}/jscpd-sarif.json"

# clean up
rm -rf "${tmpdir}"
