#!/bin/bash

set -euo pipefail
which pmd > /dev/null || exit 1

source=$1
pmd_version=$(pmd --version | grep PMD | awk '{print $2}')
brew_prefix=$(brew --prefix)
set -eo pipefail

tmpdir=$(mktemp -d)


for language in cpp cs java python ruby typescript; do
    pmd cpd --minimum-tokens=100 -l $language -d "$source" --no-fail-on-error --ignore-identifiers -f csv | \
    grep -v "lines,tokens,occurrences" \
    >> "${tmpdir}/output.csv" || true
done

awk -F ',' '{print $1, $4, $5}' "${tmpdir}/output.csv" | while read -r lines start_line file; do
    end_line=$(($start_line + $lines))
    printf "duplication,note,code duplication found in source files,%s,%s,%s\n" "${file}" "${start_line}" "${end_line}"  >> "${tmpdir}/findings.csv"
done

PATH="${brew_prefix}/opt/statica/libexec:.:$PATH" csv2sarif "pmd-cp" "${pmd_version}" "${tmpdir}/findings.csv"

rm -rf "${tmpdir}"