name: Acceptance Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read  # only need to checkout the repo and clone WebGoat over HTTPS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-22.04', 'macos-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Ensure Ruby and Bundle exist on Linux
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        bundler-cache: true

    - name: Install dependencies and run test
      run: make acceptance
      env:
        GH_TOKEN: ${{ github.token }}

    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: report-${{ matrix.os }}
        path: WebGoat/statica.html
