name: Acceptance Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read  # only need to checkout the repo and clone WebGoat over HTTPS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-22.04', 'macos-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Ensure Ruby and Bundle exist on Linux
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        bundler-cache: true

    - name: Install dependencies and run test
      run: make acceptance
      env:
        GH_TOKEN: ${{ github.token }}

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: report-${{ matrix.os }}
        path: WebGoat/statica.html
