name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and run test
      run: make acceptance
      env:
        GH_TOKEN: ${{ github.token }}
    - uses: actions/upload-artifact@v4
      with:
        name: report
        path: WebGoat/statica.html
