#!/bin/bash

source=$1
tmpdir=$(mktemp -d)
OUTPUT="${tmpdir}"/churned
TOP_N_CHURNED_FILES=10
which -s git || exit 1

git -C "${source}" log --format=format: --name-only --since=12.month \
 | egrep -v '^$' \
 | sort \
 | uniq -c \
 | sort -nr \
 | head -${TOP_N_CHURNED_FILES} \
 | awk '{print $2, $1}' > "${OUTPUT}"

# output to JSON
while read -r filename _commits; do

  cat <<-EOF >> "${tmpdir}"/findings.json
  {
      "ruleId": "top-file-churns",
      "level": "note",
      "message": {
          "text": "File has been committed to frequently. This may indicate design issues."
      },
      "locations": [
          {
              "physicalLocation": {
                  "artifactLocation": {
                      "uri": "$filename"
                  },
                  "region": {
                      "startLine": 0
                  }
              }
          }
      ]
  },
	EOF
done < "${OUTPUT}"

cat <<-EOF
  {
      "version": "2.1.0",
      "runs": [
          {
              "tool": {
                  "driver": {
                      "name": "churn",
                      "informationUri": "https://google.com/search?code+churn",
                      "rules": []
                  }
              },
              "results": [$(sed '$ s/,$//' "${tmpdir}"/findings.json)]
          }
      ]
  }
EOF

# clean up
rm -rf "${tmpdir}"
